Implemented Bocquet et al. 2016 multiplicity function.
NumCosmo/NumCosmo pull request #48
Opened 2021-08-23 01:00 UTC by pennalima

Two new functions in NcMultiplicityFunc: has_correction_factor and correction_factor. Bocquet provides fits for mean and critical mass definitions,
but the latter depends on the first.

2021-09-06 14:28 UTC, pennalima commented
@vitenti , PR ready to review!

2021-09-10 18:18 UTC, vitenti requested changes
Please check and add if all new objects have the appropriated ncm_cfg_register_obj call in ncm_cfg.c

2021-09-10 18:18 UTC, vitenti commented on numcosmo/math/ncm_cfg.c
> +#include "lss/nc_multiplicity_func_bocquet.h"
Missing the ncm_cfg_register_obj call for these new objects.

2021-09-10 18:37 UTC, vitenti approved these changes

2021-09-10 18:38 UTC, merged